storage: /verdaccio/storage
auth:
  htpasswd:
    file: /verdaccio/conf/passwdFile
uplinks:
  taobao_npmjs:
    url: https://registry.npm.taobao.org/
  npmjs:
    url: https://www.npmjs.org/
packages:
  # '@*/*':
  #   access: $all
  #   publish: $authenticated
  #   proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: taobao_npmjs npmjs
logs:
  - {type: stdout, format: pretty, level: http}
